package com.gaumala.openjisho.frontend.radicals

data class RadicalIndex(val unicodeChar: String,
                        val key: String,
                        val strokes: Int,
                        val buttonState: RadicalButtonState) {
    constructor(unicodeChar: String, key: String, strokes: Int)
            : this (unicodeChar, key, strokes, RadicalButtonState.enabled)

    constructor(unicodeChar: String, strokes: Int)
            : this (unicodeChar, unicodeChar, strokes, RadicalButtonState.enabled)

    companion object {

        fun listAll(): List<RadicalIndex>  {
           return listOf(
               RadicalIndex("一", 1),
               RadicalIndex("｜", 1),
               RadicalIndex("丶", 1),
               RadicalIndex("ノ", 1),
               RadicalIndex("乙", 1),
               RadicalIndex("亅", 1),

               RadicalIndex("二", 2),
               RadicalIndex("亠", 2),
               RadicalIndex("人", 2),
               RadicalIndex("⺅", "化", 2),
               RadicalIndex("𠆢", "个", 2),
               RadicalIndex("儿", 2),
               RadicalIndex("入", 2),
               RadicalIndex("ハ", 2),
               RadicalIndex("丷", "并", 2),
               RadicalIndex("冂", 2),
               RadicalIndex("冖", 2),
               RadicalIndex("冫", 2),
               RadicalIndex("几", 2),
               RadicalIndex("凵", 2),
               RadicalIndex("刀", 2),
               RadicalIndex("⺉", "刈", 2),
               RadicalIndex("力", 2),
               RadicalIndex("勹", 2),
               RadicalIndex("匕", 2),
               RadicalIndex("匚", 2),
               RadicalIndex("十", 2),
               RadicalIndex("卜", 2),
               RadicalIndex("卩", 2),
               RadicalIndex("厂", 2),
               RadicalIndex("厶", 2),
               RadicalIndex("又", 2),
               RadicalIndex("マ", 2),
               RadicalIndex("九", 2),
               RadicalIndex("ユ", 2),
               RadicalIndex("乃", 2),
               RadicalIndex("𠂉", "乞", 2),

               RadicalIndex("⻌", "込", 3),
               RadicalIndex("口", 3),
               RadicalIndex("囗", 3),
               RadicalIndex("土", 3),
               RadicalIndex("士", 3),
               RadicalIndex("夂", 3),
               RadicalIndex("大", 3),
               RadicalIndex("女", 3),
               RadicalIndex("子", 3),
               RadicalIndex("宀", 3),
               RadicalIndex("寸", 3),
               RadicalIndex("小", 3),
               RadicalIndex("⺌", "尚", 3),
               RadicalIndex("尢", 3),
               RadicalIndex("尸", 3),
               RadicalIndex("屮", 3),
               RadicalIndex("山", 3),
               RadicalIndex("川", 3),
               RadicalIndex("巛", 3),
               RadicalIndex("工", 3),
               RadicalIndex("已", 3),
               RadicalIndex("巾", 3),
               RadicalIndex("干", 3),
               RadicalIndex("幺", 3),
               RadicalIndex("广", 3),
               RadicalIndex("廴", 3),
               RadicalIndex("廾", 3),
               RadicalIndex("弋", 3),
               RadicalIndex("弓", 3),
               RadicalIndex("ヨ", 3),
               RadicalIndex("彑", 3),
               RadicalIndex("彡", 3),
               RadicalIndex("彳", 3),
               RadicalIndex("⺖", "忙", 3),
               RadicalIndex("⺘", "扎", 3),
               RadicalIndex("⺡", "汁", 3),
               RadicalIndex("⺨", "犯", 3),
               RadicalIndex("⺾", "艾", 3),
               RadicalIndex("⻏", "邦", 3),
               RadicalIndex("⻖", "阡", 3),
               RadicalIndex("也", 3),
               RadicalIndex("亡", 3),
               RadicalIndex("及", 3),
               RadicalIndex("久", 3),

               RadicalIndex("⺹", "老", 4),
               RadicalIndex("心", 4),
               RadicalIndex("戈", 4),
               RadicalIndex("戸", 4),
               RadicalIndex("手", 4),
               RadicalIndex("支", 4),
               RadicalIndex("攵", 4),
               RadicalIndex("文", 4),
               RadicalIndex("斗", 4),
               RadicalIndex("斤", 4),
               RadicalIndex("方", 4),
               RadicalIndex("无", 4),
               RadicalIndex("日", 4),
               RadicalIndex("曰", 4),
               RadicalIndex("月", 4),
               RadicalIndex("木", 4),
               RadicalIndex("欠", 4),
               RadicalIndex("止", 4),
               RadicalIndex("歹", 4),
               RadicalIndex("殳", 4),
               RadicalIndex("比", 4),
               RadicalIndex("毛", 4),
               RadicalIndex("氏", 4),
               RadicalIndex("气", 4),
               RadicalIndex("水", 4),
               RadicalIndex("火", 4),
               RadicalIndex("⺣", 4),
               RadicalIndex("爪", 4),
               RadicalIndex("父", 4),
               RadicalIndex("爻", 4),
               RadicalIndex("爿", 4),
               RadicalIndex("片", 4),
               RadicalIndex("牛", 4),
               RadicalIndex("犬", 4),
               RadicalIndex("⺭", "礼", 4),
               RadicalIndex("王", 4),
               RadicalIndex("元", 4),
               RadicalIndex("井", 4),
               RadicalIndex("勿", 4),
               RadicalIndex("尤", 4),
               RadicalIndex("五", 4),
               RadicalIndex("屯", 4),
               RadicalIndex("巴", 4),
               RadicalIndex("毋", 4),

               RadicalIndex("玄", 5),
               RadicalIndex("瓦", 5),
               RadicalIndex("甘", 5),
               RadicalIndex("生", 5),
               RadicalIndex("用", 5),
               RadicalIndex("田", 5),
               RadicalIndex("疋", 5),
               RadicalIndex("疒", "疔", 5),
               RadicalIndex("癶", 5),
               RadicalIndex("白", 5),
               RadicalIndex("皮", 5),
               RadicalIndex("皿", 5),
               RadicalIndex("目", 5),
               RadicalIndex("矛", 5),
               RadicalIndex("矢", 5),
               RadicalIndex("石", 5),
               RadicalIndex("示", 5),
               RadicalIndex("禸", "禹", 5),
               RadicalIndex("禾", 5),
               RadicalIndex("穴", 5),
               RadicalIndex("立", 5),
               RadicalIndex("⻂", "初", 5),
               RadicalIndex("世", 5),
               RadicalIndex("巨", 5),
               RadicalIndex("冊", 5),
               RadicalIndex("母", 5),
               RadicalIndex("⺲", "買", 5),
               RadicalIndex("牙", 5),

               RadicalIndex("瓜", 6),
               RadicalIndex("竹", 6),
               RadicalIndex("米", 6),
               RadicalIndex("糸", 6),
               RadicalIndex("缶", 6),
               RadicalIndex("羊", 6),
               RadicalIndex("羽", 6),
               RadicalIndex("而", 6),
               RadicalIndex("耒", 6),
               RadicalIndex("耳", 6),
               RadicalIndex("聿", 6),
               RadicalIndex("肉", 6),
               RadicalIndex("自", 6),
               RadicalIndex("至", 6),
               RadicalIndex("臼", 6),
               RadicalIndex("舌", 6),
               RadicalIndex("舟", 6),
               RadicalIndex("艮", 6),
               RadicalIndex("色", 6),
               RadicalIndex("虍", 6),
               RadicalIndex("虫", 6),
               RadicalIndex("血", 6),
               RadicalIndex("行", 6),
               RadicalIndex("西", 6),

               RadicalIndex("臣", 7),
               RadicalIndex("見", 7),
               RadicalIndex("角", 7),
               RadicalIndex("言", 7),
               RadicalIndex("谷", 7),
               RadicalIndex("豆", 7),
               RadicalIndex("豕", 7),
               RadicalIndex("豸", 7),
               RadicalIndex("貝", 7),
               RadicalIndex("赤", 7),
               RadicalIndex("走", 7),
               RadicalIndex("足", 7),
               RadicalIndex("身", 7),
               RadicalIndex("車", 7),
               RadicalIndex("辛", 7),
               RadicalIndex("辰", 7),
               RadicalIndex("酉", 7),
               RadicalIndex("釆", 7),
               RadicalIndex("里", 7),
               RadicalIndex("舛", 7),
               RadicalIndex("麦", 7),

               RadicalIndex("金", 8),
               RadicalIndex("長", 8),
               RadicalIndex("門", 8),
               RadicalIndex("隶", 8),
               RadicalIndex("隹", 8),
               RadicalIndex("雨", 8),
               RadicalIndex("青", 8),
               RadicalIndex("非", 8),
               RadicalIndex("奄", 8),
               RadicalIndex("岡", 8),
               RadicalIndex("免", 8),
               RadicalIndex("斉", 8),

               RadicalIndex("面", 9),
               RadicalIndex("革", 9),
               RadicalIndex("韭", 9),
               RadicalIndex("音", 9),
               RadicalIndex("頁", 9),
               RadicalIndex("風", 9),
               RadicalIndex("飛", 9),
               RadicalIndex("食", 9),
               RadicalIndex("首", 9),
               RadicalIndex("香", 9),
               RadicalIndex("品", 9),

               RadicalIndex("馬", 10),
               RadicalIndex("骨", 10),
               RadicalIndex("高", 10),
               RadicalIndex("髟", 10),
               RadicalIndex("鬥", 10),
               RadicalIndex("鬯", 10),
               RadicalIndex("鬲", 10),
               RadicalIndex("鬼", 10),
               RadicalIndex("竜", 10),
               RadicalIndex("韋", 10),

               RadicalIndex("魚", 11),
               RadicalIndex("鳥", 11),
               RadicalIndex("鹵", 11),
               RadicalIndex("鹿", 11),
               RadicalIndex("麻", 11),
               RadicalIndex("亀", 11),
               RadicalIndex("啇", "滴", 11),
               RadicalIndex("黄", 11),
               RadicalIndex("黒", 11),

               RadicalIndex("黍", 12),
               RadicalIndex("黹", 12),
               RadicalIndex("無", 12),
               RadicalIndex("歯", 12),

               RadicalIndex("黽", 13),
               RadicalIndex("鼎", 13),
               RadicalIndex("鼓", 13),
               RadicalIndex("鼠", 13),

               RadicalIndex("鼻", 14),
               RadicalIndex("齊", 14),

               RadicalIndex("龠", 17)
            )
        }
    }
}